---
title: "Practice Problems"
format: html
---

# Load Libraries

```{r}
library(tidyverse)
library(rethinking)
```

# 8E1

For each of the causal relationship below, name a hypothetical third variable that would lead to an interaction effect.

1.  Bread dough rises because of yeast.
    1.  Temperature - Too cold or hot an the bacteria die, somewhere there is a sweet-spot for it
2.  Education leads to higher income.
    1.  
3.  Gasoline makes a car go.

# 8E2

Which of the following explanations invokes an interaction?

1.  Caramelizing onions requires cooking over low heat and making sure the onions do not dry out.
2.  A car will go faster when it has more cylinders or when it has a better fuel injector.
3.  Most people acquire their political beliefs from their parents, unless they get them instead from their friends.
4.  Intelligent animal species tend to either be highly social or have manipulative appendages (hands, tentacles, etc.)

# 8E3

For each of the explanations in **8E2**, write a linear model that expresses the stated relationship.

# 8M1

Recall the tulips example from the chapter. Suppose another set of treatments adjusted the temperature in the greenhouse over two levels: cold and hot. The data in the chapter were collected at the cold temperature. You find none of the plants grown under the hot temperature developed any blooms at all, regardless of the water and shade levels. Can you explain this result in terms of interactions between water, shade, and temperature?

# 8M2

Can you invent a regression equation that would make the bloom size zero, whenever the temperature is hot?

# 8M3

In parts of North America, ravens depend upon wolves for their food. This is because ravens are carnivorous but cannot usually kill or open carcasses of prey. Wolves however can and do kill and tear open animals, and they tolerate ravens co-feeding at their kills. This species relationship is generally described as a "species interaction." Can you invent a hypothetical set of data on raven populations size in which this relationship would manifest as a statistical interaction? Do you think the biological interaction could be linear? Why or why not?

# 8M4

Repeat the tulips analysis, but this time use priors that constrain the effect of water to be positive and the effect of shade to be negative. Use prior predictive simulation. What do these prior assumptions mean for the interaction prior, if anything?

# 8H1

# 8H2

# 8H3

# 8H4

# 8H5

# 8H6
